dist: trusty
sudo: required
language: bash

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash

install: ./install_deps.sh

script:
- mkdir -p /home/travis/.ssh/ ; touch /home/travis/.ssh/appuser.pub
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- cd terraform/prod ; terraform init -backend=false ; terraform validate --var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd ../stage ; terraform init -backend=false ; terraform validate --var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd ../../ansible ; ansible-lint playbooks/*.yml --exclude=roles/jdauphant.nginx

notifications:
  slack:
    rooms:
      secure: JABlD8cnkt+CEdUoeqlWRRs74wTfdFGCZXtZ0lrxyeNQleiQh/GGvnN178oMbUI9ktseFBaj8Kt3dCcWhpFeBbpn6nzaJbOWVBJKoBzhpwSDmB316L4TC3XQsiW0hFxP3kAxiuthih2pskhQQpxJbGfLOXXMBnmqBr6HU32bGhsQob31Wn5e6jvQeTuXh4doZY0Ur3JBJTlpPlezbOXbdjPsSLE0HKGkEjw1cTSHGah78RiWkY3QsE8mFa3HD0aLmpVh507LBObKSgJ5ShefK8PSZXK6KqL2YFBMXnKbNtMItyp7ZuiUss5P3lWkKjHNgGEd0xx1QrmefyoknidesKhgnsGhvjwU6M3EzFIrIk6zh1O9SIJni7mDFp3SSyTT7Vt5IEVV2zOK7nmLRZOuChmnRkwhyA2gACa9WE4cx1xnzZGZtW5GE5H96pTvQRZX0SUbCFuuEVPDVKasithljdlKPoiI+SYF06ntJJyOKXBL5rpzuP04hJlL/USxbPsOvq/YZ06BzVrEkH7+RKMQtvFGt+KltClTkLoJFcBML+s4FWcwLu1YxsVG1TfMDUti+xxzk3XfAoShq9fzWkM07AkW1Zqj80LyaRJH6LUk+WQXTJr2d/0pQfi/Bb8wMXqjv4eGlS9kQP2z5CW48JJm6DwKEbeZZNSW8ITCz1NxDvI=
