---
- name: Configure Puma
  hosts: tag_reddit-app
  become: true
  vars:
   db_host: 10.156.0.2
  tasks:
    - name: Configure SystemD
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: puma config
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded
